---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-kubernetes
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nmm131/sba.kubernetes-cluster
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sba-kubernetes-svc
spec:
  type: NodePort
  selector:
    app: sba-kubernetes
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
    